import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { KubeConfig } from '@kubernetes/client-node';
import type { Locator, Page } from '@playwright/test';
import type { NavigationBar, Runner } from '@podman-desktop/tests-playwright';
import {
  expect,
  PreferencesPage,
  RunnerOptions,
  StatusBar,
  test,
  withMockedOpenFileDialog,
} from '@podman-desktop/tests-playwright';

const DASHBOARD_ID = 'podman-desktop.kubernetes-dashboard';
const CONTEXTS_ID = 'podman-desktop.kubernetes-contexts';
const PRIMARY_CONTEXT = 'envtest';
const SECONDARY_CONTEXT = 'e2e-secondary';
const RESTRICTED_CONTEXT = 'e2e-restricted';
const IMPORTED_CONTEXT = 'e2e-imported';
const PROFILE = 'kubernetes-contexts-tests';
const PREINSTALLED = process.env.EXTENSION_PREINSTALLED === 'true';

const sourceKubeconfig = process.env.E2E_KUBECONFIG;
const userKubeconfig = process.env.E2E_USER1_KUBECONFIG;
const profileKubeconfig = path.resolve('tests', 'playwright', 'resources', 'kube-config');
const importKubeconfig = path.resolve('tests', 'playwright', 'resources', 'import-kube-config');
const fixtures = path.resolve('..', 'resources', 'cluster-fixtures.yaml');

function loadConfig(file: string): KubeConfig {
  const config = new KubeConfig();
  config.loadFromFile(file);
  return config;
}

function kubectl(...args: string[]): void {
  if (!sourceKubeconfig) throw new Error('E2E_KUBECONFIG is required');
  const binary = path.join(
    process.env.KUBEBUILDER_ASSETS ?? '',
    process.platform === 'win32' ? 'kubectl.exe' : 'kubectl',
  );
  execFileSync(binary, ['--kubeconfig', sourceKubeconfig, ...args], { stdio: 'pipe' });
}

function prepareFixtures(): void {
  if (!sourceKubeconfig || !userKubeconfig) {
    throw new Error('Set E2E_KUBECONFIG and E2E_USER1_KUBECONFIG to files generated by envtest-start --users 1');
  }
  const config = loadConfig(sourceKubeconfig);
  const original = config.contexts.find(context => context.name === PRIMARY_CONTEXT);
  const restrictedUser = loadConfig(userKubeconfig).users[0];
  if (!original || !restrictedUser) throw new Error('envtest kubeconfig must contain envtest and user1');
  const cluster = config.clusters.find(item => item.name === original.cluster);
  const hostname = cluster ? new URL(cluster.server).hostname : '';
  if (!['127.0.0.1', 'localhost', '[::1]'].includes(hostname)) {
    throw new Error('E2E_KUBECONFIG must point to a local envtest API server');
  }
  kubectl('apply', '-f', fixtures);

  config.contexts.push({ ...original, name: SECONDARY_CONTEXT, namespace: 'kube-system' });
  config.users.push({ ...restrictedUser, name: 'e2e-restricted-user' });
  config.contexts.push({ ...original, name: RESTRICTED_CONTEXT, user: 'e2e-restricted-user', namespace: 'default' });

  fs.mkdirSync(path.dirname(profileKubeconfig), { recursive: true });
  fs.writeFileSync(profileKubeconfig, config.exportConfig());

  const toImport = new KubeConfig();
  toImport.loadFromOptions({
    clusters: config.clusters,
    users: config.users,
    contexts: [
      { ...original, name: SECONDARY_CONTEXT, namespace: 'imported-namespace' },
      { ...original, name: IMPORTED_CONTEXT, namespace: 'default' },
    ],
    currentContext: IMPORTED_CONTEXT,
  });
  fs.writeFileSync(importKubeconfig, toImport.exportConfig());
}

async function contextsWebview(runner: Runner, page: Page, navigationBar: NavigationBar): Promise<Page> {
  await navigationBar.navigationLocator.getByRole('link', { name: 'Contexts', exact: true }).click();
  await expect(page.getByRole('document', { name: 'Webview Contexts' })).toBeVisible();
  await expect
    .poll(async () => {
      for (const window of runner.getWindows().slice(1)) {
        if ((await window.getByRole('heading', { name: 'Kubernetes Contexts' }).count()) > 0) return true;
      }
      return false;
    })
    .toBe(true);
  for (const window of runner.getWindows().slice(1)) {
    if ((await window.getByRole('heading', { name: 'Kubernetes Contexts' }).count()) > 0) return window;
  }
  throw new Error('Contexts webview was not found');
}

test.use({
  runnerOptions: new RunnerOptions({
    customFolder: PROFILE,
    customSettings: {
      'extensions.disabled': [
        'podman-desktop.compose',
        'podman-desktop.docker',
        'podman-desktop.kind',
        'podman-desktop.kubectl-cli',
        'podman-desktop.lima',
        'podman-desktop.minikube',
        'podman-desktop.registries',
      ],
    },
  }),
});

test.describe.serial('Kubernetes Contexts with Dashboard stopped, then started', { tag: '@integration' }, () => {
  let webview: Page;

  test.beforeAll(async ({ runner, welcomePage }) => {
    test.setTimeout(120_000);
    prepareFixtures();
    runner.setVideoAndTraceName('kubernetes-contexts-e2e');
    await welcomePage.handleWelcomePage(true);
  });

  test.afterAll(async ({ runner }) => {
    test.setTimeout(120_000);
    await runner.close();
  });

  test('install both extensions and stop Dashboard before Contexts starts', async ({ navigationBar }) => {
    test.setTimeout(180_000);
    await test.step('Dashboard is disabled while Kubernetes Contexts stays active', async () => {
      const extensions = await navigationBar.openExtensions();
      await expect(extensions.header).toBeVisible();

      if (!PREINSTALLED) {
        const dashboardImage =
          process.env.DASHBOARD_OCI_IMAGE ??
          'ghcr.io/podman-desktop/podman-desktop-extension-kubernetes-dashboard:0.6.0';
        await extensions.installExtensionFromOCIImage(dashboardImage);
      }
      const dashboard = await extensions.getInstalledExtension('Kubernetes Dashboard', DASHBOARD_ID);
      await expect(dashboard.status).toHaveText('ACTIVE');
      await dashboard.disableExtension();
      await expect(dashboard.status).toHaveText('DISABLED');

      if (!PREINSTALLED) {
        const contextsImage = process.env.EXTENSION_OCI_IMAGE;
        if (!contextsImage) throw new Error('Set EXTENSION_OCI_IMAGE or EXTENSION_PREINSTALLED=true');
        await extensions.installExtensionFromOCIImage(contextsImage);
      }
      const contexts = await extensions.getInstalledExtension('Kubernetes Contexts', CONTEXTS_ID);
      await expect(contexts.status).toHaveText('ACTIVE');
      if (PREINSTALLED) {
        // Both plugins may activate during startup. Restart Contexts with Dashboard disabled
        // so no cached Dashboard health or resource events survive the standalone phase.
        await contexts.disableExtension();
        await contexts.enableExtension();
      }
      await expect(dashboard.status, 'Dashboard is disabled while Kubernetes Contexts stays active').toHaveText(
        'DISABLED',
      );
    });
  });

  test('load isolated kubeconfig and show contexts without Dashboard data', async ({ runner, page, navigationBar }) => {
    await test.step('Contexts are available without Dashboard health or resource data', async () => {
      const settings = await navigationBar.openSettings();
      await settings.expandPreferencesTab();
      const preferences = await settings.openTabPage(PreferencesPage);
      await preferences.selectKubeFile(profileKubeconfig);
      await new StatusBar(page).validateKubernetesContext(PRIMARY_CONTEXT);

      webview = await contextsWebview(runner, page, navigationBar);
      await expect(webview.getByRole('table', { name: 'Contexts' })).toBeVisible();
      const primary = webview.getByRole('row', { name: PRIMARY_CONTEXT, exact: true });
      await expect(primary.getByLabel('Current Context')).toBeVisible();
      await expect(primary.getByRole('button', { name: `Connect to context ${PRIMARY_CONTEXT}` })).toBeVisible();
      await expect(webview.getByRole('row', { name: SECONDARY_CONTEXT, exact: true })).toBeVisible();
      await expect(webview.getByRole('row', { name: RESTRICTED_CONTEXT, exact: true })).toBeVisible();
      await expect(
        primary.getByLabel('Context Unknown'),
        'Contexts are available without Dashboard health or resource data',
      ).toHaveText('UNKNOWN');
    });
  });

  test('switch, duplicate, edit, and delete contexts without Dashboard', async ({ page }) => {
    test.setTimeout(150_000);
    const primary = webview.getByRole('row', { name: PRIMARY_CONTEXT, exact: true });
    const copy = webview.getByRole('row', { name: `${PRIMARY_CONTEXT}-1`, exact: true });
    const edited = webview.getByRole('row', { name: 'e2e-edited', exact: true });

    await test.step('The primary context is restored after switching contexts', async () => {
      const secondary = webview.getByRole('row', { name: SECONDARY_CONTEXT, exact: true });
      await secondary.getByRole('button', { name: 'Set as Current Context' }).click();
      await expect(secondary.getByLabel('Current Context')).toBeVisible();
      await expect.poll(() => loadConfig(profileKubeconfig).getCurrentContext()).toBe(SECONDARY_CONTEXT);

      await primary.getByRole('button', { name: 'Set as Current Context' }).click();
      await expect.poll(() => loadConfig(profileKubeconfig).getCurrentContext()).toBe(PRIMARY_CONTEXT);
      await expect(
        primary.getByLabel('Current Context'),
        'The primary context is restored after switching contexts',
      ).toBeVisible();
    });

    await test.step('The duplicated context appears in the list', async () => {
      await primary.getByRole('button', { name: 'Duplicate Context' }).click();
      await expect(copy).toBeVisible();
      await expect
        .poll(() => loadConfig(profileKubeconfig).contexts.some(context => context.name === `${PRIMARY_CONTEXT}-1`))
        .toBe(true);
      await expect(copy, 'The duplicated context appears in the list').toBeVisible();
    });

    await test.step('The edited context has its new name and namespace', async () => {
      await copy.getByRole('button', { name: 'Edit Context' }).click();
      const edit = webview.getByRole('dialog', { name: 'Edit Context' });
      await edit.getByRole('textbox', { name: 'contextName', exact: true }).fill('e2e-edited');
      await edit.getByRole('textbox', { name: 'contextNamespace', exact: true }).fill('e2e-namespace');
      await edit.getByRole('button', { name: 'Save' }).click();
      await expect(edited).toBeVisible();
      await expect
        .poll(() => loadConfig(profileKubeconfig).contexts.find(context => context.name === 'e2e-edited')?.namespace)
        .toBe('e2e-namespace');
      await expect(edited, 'The edited context has its new name and namespace').toContainText('e2e-namespace');
    });

    await test.step('The deleted context disappears from the list', async () => {
      await edited.getByRole('button', { name: 'Delete Context' }).click();
      const confirmation = page.getByRole('dialog');
      await expect(confirmation).toContainText('e2e-edited');
      await confirmation.getByRole('button', { name: 'Yes' }).click();
      await expect(edited).not.toBeVisible();
      await expect
        .poll(() => loadConfig(profileKubeconfig).contexts.some(context => context.name === 'e2e-edited'))
        .toBe(false);
      await expect(edited, 'The deleted context disappears from the list').not.toBeVisible();
    });
  });

  // CDP cannot mock Electron's native file dialog; restore this test when a CDP-compatible picker is available.
  test.skip('import contexts with keep-both and replace conflict choices', async () => {
    test.setTimeout(120_000);
    async function openImport(): Promise<Locator> {
      await webview.getByRole('button', { name: 'Import', exact: true }).click();
      const dialog = webview.getByRole('dialog', { name: 'Import Kubeconfig' });
      await expect(dialog).toBeVisible();
      await withMockedOpenFileDialog([importKubeconfig], async () => {
        await dialog.getByRole('button', { name: 'Browse for file' }).click();
        await expect(dialog.getByRole('textbox', { name: 'Kubeconfig file path' })).toHaveValue(importKubeconfig);
      });
      await expect(dialog.getByText('Found 2 contexts in the file:')).toBeVisible();
      return dialog;
    }

    await test.step('A conflicting context is kept under a new name', async () => {
      const firstImport = await openImport();
      await expect(firstImport.getByRole('row', { name: SECONDARY_CONTEXT }).getByText('Keep both')).toBeVisible();
      await firstImport.getByRole('button', { name: 'Import contexts' }).click();
      await expect(webview.getByRole('row', { name: `${SECONDARY_CONTEXT}-1`, exact: true })).toBeVisible();
      await expect(webview.getByRole('row', { name: IMPORTED_CONTEXT, exact: true })).toBeVisible();
      await expect
        .poll(() => loadConfig(profileKubeconfig).contexts.some(context => context.name === `${SECONDARY_CONTEXT}-1`))
        .toBe(true);
      await expect(
        webview.getByRole('row', { name: `${SECONDARY_CONTEXT}-1`, exact: true }),
        'A conflicting context is kept under a new name',
      ).toBeVisible();
    });

    await test.step('A conflicting context replaces the existing one', async () => {
      const secondImport = await openImport();
      await secondImport.getByRole('row', { name: IMPORTED_CONTEXT }).getByRole('checkbox').uncheck();
      await secondImport
        .getByRole('row', { name: SECONDARY_CONTEXT })
        .getByRole('radio', { name: 'replace-conflict-resolution-select' })
        .check({ force: true });
      await secondImport.getByRole('button', { name: 'Import contexts' }).click();
      await expect
        .poll(
          () => loadConfig(profileKubeconfig).contexts.find(context => context.name === SECONDARY_CONTEXT)?.namespace,
        )
        .toBe('imported-namespace');
      await expect(
        webview.getByRole('row', { name: SECONDARY_CONTEXT, exact: true }),
        'A conflicting context replaces the existing one',
      ).toContainText('imported-namespace');
    });
  });

  test('start Dashboard and display context health and resource counts', async ({ runner, page, navigationBar }) => {
    test.setTimeout(120_000);
    await test.step('Dashboard adds context health and Kubernetes resource counts', async () => {
      const extensions = await navigationBar.openExtensions();
      const dashboard = await extensions.getInstalledExtension('Kubernetes Dashboard', DASHBOARD_ID);
      await expect(dashboard.status).toHaveText('DISABLED');
      await dashboard.enableExtension();
      await expect(dashboard.status).toHaveText('ACTIVE');

      webview = await contextsWebview(runner, page, navigationBar);
      const primary = webview.getByRole('row', { name: PRIMARY_CONTEXT, exact: true });
      await expect(primary.getByLabel('Context Reachable')).toHaveText('REACHABLE', { timeout: 60_000 });
      await expect(primary.getByLabel('Context Pods Count')).toHaveText('1', { timeout: 60_000 });
      await expect(
        primary.getByLabel('Context Deployments Count'),
        'Dashboard adds context health and Kubernetes resource counts',
      ).toHaveText('1', { timeout: 60_000 });
    });
  });

  test('show Dashboard permissions for a restricted context', async () => {
    test.setTimeout(120_000);
    await test.step('Dashboard shows restricted permissions for the user1 context', async () => {
      const restricted = webview.getByRole('row', { name: RESTRICTED_CONTEXT, exact: true });
      const connect = restricted.getByRole('button', { name: `Connect to context ${RESTRICTED_CONTEXT}` });
      const reachable = restricted.getByLabel('Context Reachable');
      await expect.poll(async () => (await connect.isVisible()) || (await reachable.isVisible())).toBe(true);
      if (await connect.isVisible()) await connect.click();
      await expect(reachable).toHaveText('REACHABLE', { timeout: 60_000 });
      await expect(restricted.getByLabel('Context Pods Count')).toHaveText('1', { timeout: 60_000 });
      await expect(
        restricted.getByLabel('Context Deployments Count'),
        'Dashboard shows restricted permissions for the user1 context',
      ).toHaveText('-', { timeout: 60_000 });
    });
  });
});
